// build.mjs — packs game.html + its sibling ES modules (three.module.js, fleet-heavy.js,
// fleet-light.js, sfx.js) into ONE self-contained, double-clickable NavalDominance.html.
//
// How: each module's UTF-8 source is embedded as base64; at runtime a tiny prelude decodes
// them into Blobs and rewrites the MODULES registry with blob: URLs. Dynamic `import()` of a
// blob URL works even on file:// pages (where ordinary relative module imports are blocked
// by CORS), which is what makes the output openable with a plain double-click.
//
// Usage:  node build.mjs        (run from naval-dominance/)
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const dir = dirname(fileURLToPath(import.meta.url));
const read = f => readFileSync(join(dir, f), 'utf8');
const b64 = f => Buffer.from(read(f), 'utf8').toString('base64');

const MODS = {
  three:      'three.module.js',
  fleetHeavy: 'fleet-heavy.js',
  fleetLight: 'fleet-light.js',
  sfx:        'sfx.js',
  gltfLoader: 'gltf-loader.js',   // note: imports './three.module.js' — rewritten to the three blob URL at runtime
  fleetReal:  'fleet-real.js',
};

let html = read('game.html');

// the prelude that replaces the registry at runtime (injected at the __EMBED_HOOK__ marker)
const embeds = Object.entries(MODS)
  .map(([k, f]) => `${k}:"${b64(f)}"`)
  .join(',\n');
const prelude = `
// ---- STANDALONE BUILD (generated by build.mjs — do not edit by hand) ----
const __B64={${embeds}};
const __bytes=b64=>{ const bin=atob(b64), bytes=new Uint8Array(bin.length);
  for(let i=0;i<bin.length;i++) bytes[i]=bin.charCodeAt(i); return bytes; };
const __blobURL=bytes=>URL.createObjectURL(new Blob([bytes],{type:'text/javascript'}));
const __threeURL=__blobURL(__bytes(__B64.three));
// gltf-loader imports './three.module.js' — rewrite its specifier to the three blob URL
const __loaderSrc=new TextDecoder().decode(__bytes(__B64.gltfLoader)).replaceAll('./three.module.js',__threeURL);
MODULES={ three:__threeURL,
  fleetHeavy:__blobURL(__bytes(__B64.fleetHeavy)), fleetLight:__blobURL(__bytes(__B64.fleetLight)),
  sfx:__blobURL(__bytes(__B64.sfx)),
  gltfLoader:URL.createObjectURL(new Blob([__loaderSrc],{type:'text/javascript'})),
  fleetReal:__blobURL(__bytes(__B64.fleetReal)) };
`;

const HOOK = '/*__EMBED_HOOK__*/';
if (!html.includes(HOOK)) { console.error('EMBED_HOOK marker not found in game.html'); process.exit(1); }
html = html.replace(HOOK, prelude);
html = html.replace('<title>NAVAL DOMINANCE</title>', '<title>NAVAL DOMINANCE (standalone)</title>');

writeFileSync(join(dir, 'NavalDominance.html'), html);
console.log('WROTE NavalDominance.html —', (html.length / 1024 / 1024).toFixed(2), 'MB');
